---
galaxy_info:
  author: Jim McCann
  description: Deploy nested vCenter VMs from OVA with DHCP and SSO configuration
  company: Red Hat

  license: Apache-2.0

  min_ansible_version: "2.9"

  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all

  galaxy_tags:
    - vmware
    - vsphere
    - vcenter
    - nested
    - virtualization

dependencies: []
