---
galaxy_info:
  author: Jim McCann
  description: Manage cron jobs for automated cleanup of nested vSphere environments
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - vmware
    - vsphere
    - lifecycle
    - cron
    - automation

dependencies: []
