---
# defaults file for resource_validation

# Resources to reserve on parent cluster (resources above this threshold trigger failure)
resource_validation_cpu_reserved: 20000     # MHz to reserve
resource_validation_memory_reserved: 98304  # MB to reserve  (96 GB)
resource_validation_storage_reserved: 1000000  # MB to reserve (976 GB)
