---
galaxy_info:
  author: Jim McCann
  description: Configure VMFS datastores and NFS mounts for nested ESXi hosts
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - vmware
    - vsphere
    - storage
    - vmfs
    - nfs

dependencies: []
