---
galaxy_info:
  author: Jim McCann
  description: Create datacenter and cluster structure in nested vCenter with DRS/HA
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - vmware
    - vsphere
    - vcenter
    - datacenter
    - cluster

dependencies: []
