---
# defaults file for vcenter_networking

vcenter_datacenter_name: "nested-devqedatacenter-1"
vcenter_cluster_name: "nested-devqecluster-1"
vcenter_networking_dvs_enabled: true
vcenter_networking_dvs_name: "dvSwitch-nested"
vcenter_networking_dvs_version: "8.0.0"
vcenter_networking_dvs_mtu: 9000
vcenter_networking_dvs_uplinks: 1
vcenter_networking_dvs_uplink_nics:
  - vmnic1
vcenter_networking_portgroup_name: "devqe-922"
vcenter_networking_portgroup_vlan_id: 0
vcenter_networking_portgroup_num_ports: 120
vcenter_networking_portgroup_binding: "static"
vcenter_networking_pause_after_dvs: 10
vcenter_networking_pause_after_host: 10
