---
galaxy_info:
  author: Jim McCann
  description: Add ESXi hosts to vCenter and configure power management, autostart, and vMotion
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - vmware
    - vsphere
    - esxi
    - vcenter
    - configuration

dependencies: []
